FROM nvcr.io/nvidia/pytorch:24.02-py3

# ARG USERNAME=<<user>>
# ARG WORKING_DIR=<<working-dir>>
# ARG USER_UID=<<uid>>
# ARG USER_GID=<<gid>>
# ARG POETRY_VERSION=<<poetry-version>>

ARG USERNAME=mike
ARG WORKING_DIR=/home/mike/pytorch-poetry-hydra-template
ARG USER_UID=1002
ARG USER_GID=1002
ARG POETRY_VERSION=1.8.1

SHELL ["/bin/bash", "-c"]

# Use a non-root user
ARG USER_UID=${USER_UID}
ARG USER_GID=${USER_GID}

# Create the user
RUN groupadd --gid $USER_GID ${USERNAME} \
    && useradd --uid $USER_UID --gid $USER_GID -m ${USERNAME}

RUN mkdir ${WORKING_DIR}/ && \
    chown -R $USER_GID:$USER_UID ${WORKING_DIR}

# Install git/ssh/tmux
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git ssh tmux vim curl htop sudo unzip

# Give sudo privledges  to user
RUN echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}

# Install poetry
# https://python-poetry.org/docs/configuration/#using-environment-variables
USER ${USERNAME}
ENV POETRY_VERSION="${POETRY_VERSION}" \
    POETRY_HOME="/home/${USERNAME}/poetry" \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=false \
    POETRY_VIRTUALENVS_CREATE=false \
    # BUILD_PATH="/home/${USERNAME}/build" \
    # VENV_PATH="/home/${USERNAME}/build/.venv" \
    WORKING_DIR=${WORKING_DIR}
# PATH="/home/${USERNAME}/.local/bin:${PATH}" \
# VIRTUAL_ENV=$VENV_PATH

# ENV PATH="$VENV_PATH/bin:$POETRY_HOME/bin:$PATH"
RUN curl -sSL https://install.python-poetry.org | python3 - && exec bash

# Install project requirements 
# RUN mkdir ${BUILD_PATH}
# WORKDIR ${BUILD_PATH}
COPY ./ ./
RUN python -m venv .venv && \ 
    source .venv/bin/activate && \
    pip install --upgrade pip && \
    poetry install -vvv --no-root
# poetry install -vvv --no-root && \
# echo "source ${BUILD_PATH}/.venv/bin/activate" >> /home/$USERNAME/.bashrc

WORKDIR $WORKING_DIR
