defaults:
  - data: default
  - nn: default
  - optim: default
  - training: default
  - _self_ # We override group configs above with values defined in this config file!

# path configuration
paths:
  root: ${oc.env:WORKING_DIR} # Path project folder
  data_folder: ${paths.root}/data
  artifacts: ${paths.root}/artifacts
  logs: ${paths.artifacts}/logs
  checkpoints: ${paths.artifacts}/checkpoints

# wandb configs
wandb:
  log_to_wandb: True # Global switch for turning all wandb calls into no-ops, see ./src/package/utils/wandb_utils.py
  name: my-wandb-run-name  # Update as required to name run on wandb
  run_id: null  # Keep null for fresh runs, otherwise, set to run_id to load ckpt
  project: <<wandb-project>>
  entity: <<wandb-entity>>
  start_method: thread

# hydra configs
hydra:
  run:
    dir: ${paths.logs}

# logging configs
logging:
  level: info

# WARNING: The following config groups will override config groups specified in defaults!!!
# data config overrides
data:

# neural network config overrides
nn:

# training config overrides
training:
  resume: False  # Resume run from ckpt

# optimizer configs overrides
optim:

# utils configs overrides
utils:
