program: main.py
method: grid
project: <<wandb-project>>
name: your-sweep-name
metric:
  goal: maximize
  name: accuracy
parameters:
  nn:
    values: [resnet18, wide_resnet22]  # Can specify entire group configs
  data:
    value: cifar10
  training.lr: 
    values: [0.0003, 0.001, 0.1,]
  training.seed:
    values: [8746, 6037, 7303, 2078, 42]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
